use_frameworks!

platform :ios, '10.0'

target 'MyCocoapodsLibrary_Example' do
  pod 'MyCocoapodsLibrary', :path => '../'

  target 'MyCocoapodsLibrary_Tests' do
    inherit! :search_paths

    
  end
end
